//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.Desktop.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une sauvegarde.
        /// </summary>
        internal static string AddJob {
            get {
                return ResourceManager.GetString("AddJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  Ajouter.
        /// </summary>
        internal static string AddJobButton {
            get {
                return ResourceManager.GetString("AddJobButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin Destination :.
        /// </summary>
        internal static string AddJobDestination {
            get {
                return ResourceManager.GetString("AddJobDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du job :.
        /// </summary>
        internal static string AddJobName {
            get {
                return ResourceManager.GetString("AddJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin Source :.
        /// </summary>
        internal static string AddJobSource {
            get {
                return ResourceManager.GetString("AddJobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de sauvegarde (1 = Complète, 2 = Différentielle) :.
        /// </summary>
        internal static string AddJobType {
            get {
                return ResourceManager.GetString("AddJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un Job.
        /// </summary>
        internal static string AddJobWindowTitle {
            get {
                return ResourceManager.GetString("AddJobWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logiciels métier bloquant la sauvegarde (séparés par des virgules) :.
        /// </summary>
        internal static string BusinessSoftwareLabel {
            get {
                return ResourceManager.GetString("BusinessSoftwareLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs.
        /// </summary>
        internal static string ConsoleLogTitle {
            get {
                return ResourceManager.GetString("ConsoleLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Decrypt.
        /// </summary>
        internal static string DecryptLabel {
            get {
                return ResourceManager.GetString("DecryptLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string DeleteJob {
            get {
                return ResourceManager.GetString("DeleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurer l&apos;encryption.
        /// </summary>
        internal static string EncryptionConfigurationLabel {
            get {
                return ResourceManager.GetString("EncryptionConfigurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter extensions priority.
        /// </summary>
        internal static string EnterExtensionPriority {
            get {
                return ResourceManager.GetString("EnterExtensionPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter.
        /// </summary>
        internal static string ExecuteJob {
            get {
                return ResourceManager.GetString("ExecuteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executer la sélection.
        /// </summary>
        internal static string ExecuteSelectedJobLabel {
            get {
                return ResourceManager.GetString("ExecuteSelectedJobLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extension.
        /// </summary>
        internal static string ExtensionsLabel {
            get {
                return ResourceManager.GetString("ExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin Destination.
        /// </summary>
        internal static string JobDestination {
            get {
                return ResourceManager.GetString("JobDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string JobName {
            get {
                return ResourceManager.GetString("JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des Jobs.
        /// </summary>
        internal static string JobsListTitle {
            get {
                return ResourceManager.GetString("JobsListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin Source.
        /// </summary>
        internal static string JobSource {
            get {
                return ResourceManager.GetString("JobSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de Sauvegarde.
        /// </summary>
        internal static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taille maximale d&apos;un gros fichier (en Ko) :.
        /// </summary>
        internal static string LargeFileSizeLimitLabel {
            get {
                return ResourceManager.GetString("LargeFileSizeLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ⚙️Configurer les paramettres des sauvegardes.
        /// </summary>
        internal static string OpenSaveConfig {
            get {
                return ResourceManager.GetString("OpenSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Extensions prioritaires (séparées par des virgules) :.
        /// </summary>
        internal static string PriorityExtensionsLabel {
            get {
                return ResourceManager.GetString("PriorityExtensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string SaveButtonLabel {
            get {
                return ResourceManager.GetString("SaveButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Démarrer le serveur.
        /// </summary>
        internal static string StartServer {
            get {
                return ResourceManager.GetString("StartServer", resourceCulture);
            }
        }
    }
}
